Make anno aggregations part of a global resource maintenance job

diff --git a/Tekst-Util/tekst-util b/Tekst-Util/tekst-util
--- a/Tekst-Util/tekst-util
+++ b/Tekst-Util/tekst-util
@@ -34,9 +34,10 @@ tekst_util_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   Create DB backup (MongoDB service must be running)\n" "backup "
-  printf "  %s   Restore DB backup (MongoDB service must be running)\n" "restore"
-  printf "  %s   Create/update search index (MongoDB and ES services must be running)\n" "index  "
+  printf "  %s   Create DB backup (MongoDB service must be running)\n" "backup     "
+  printf "  %s   Restore DB backup (MongoDB service must be running)\n" "restore    "
+  printf "  %s   Create/update search index (MongoDB and ES services must be running)\n" "index      "
+  printf "  %s   Run resource maintenance routines (MongoDB service must be running)\n" "maintenance"
   echo
 
   # :command.long_usage
@@ -209,8 +210,55 @@ tekst_util_index_usage() {
     # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  tekst-util index\n"
-    printf "  tekst-util index -d\n"
+    printf "  tekst-util index -c tekst-api\n"
     printf "  tekst-util index --dev\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+tekst_util_maintenance_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "tekst-util maintenance - Run resource maintenance routines (MongoDB service must be running)\n"
+    echo
+
+  else
+    printf "tekst-util maintenance - Run resource maintenance routines (MongoDB service must be running)\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  tekst-util maintenance [OPTIONS]\n"
+  printf "  tekst-util maintenance --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--container-name, -c CONTAINER"
+    printf "    Tekst-API Docker container name (if using Docker)\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--dev, -d"
+    printf "    Whether Tekst is running in development mode (sets TEKST_DEV_MODE env var)\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  tekst-util maintenance\n"
+    printf "  tekst-util maintenance -c tekst-api\n"
+    printf "  tekst-util maintenance --dev\n"
     echo
 
   fi
@@ -360,6 +408,25 @@ tekst_util_index_command() {
 
 }
 
+# :command.function
+tekst_util_maintenance_command() {
+  # src/maintenance_command.sh
+  container=${args[--container-name]}
+  dev=${args[--dev]}
+
+  # if in dev mode, run python using poetry's virtual env
+  [[ $dev ]] && run_python="poetry run python" || run_python="python"
+
+  if [[ $container ]]; then
+      docker exec -e TEKST_DEV_MODE=$dev -i $container $run_python -m tekst maintenance
+  else
+      cd_to_script_parent_dir
+      cd ../Tekst-API
+      TEKST_DEV_MODE=$dev $run_python -m tekst maintenance
+  fi
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -407,6 +474,13 @@ parse_requirements() {
       action="index"
       shift
       tekst_util_index_parse_requirements "$@"
+      shift $#
+      ;;
+
+    maintenance)
+      action="maintenance"
+      shift
+      tekst_util_maintenance_parse_requirements "$@"
       shift $#
       ;;
 
@@ -697,6 +771,71 @@ tekst_util_index_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+tekst_util_maintenance_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        tekst_util_maintenance_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="maintenance"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --container-name | -c)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--container-name']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--container-name requires an argument: --container-name, -c CONTAINER" >&2
+          exit 1
+        fi
+        ;;
+
+      # :flag.case
+      --dev | -d)
+
+        # :flag.case_no_arg
+        args['--dev']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -719,6 +858,7 @@ run() {
     "backup") tekst_util_backup_command ;;
     "restore") tekst_util_restore_command ;;
     "index") tekst_util_index_command ;;
+    "maintenance") tekst_util_maintenance_command ;;
   esac
 }
 
